on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.denktmit.tech
          username: ${{ secrets.CI_ACTOR }}
          password: ${{ secrets.CI_TOKEN  }}

      - uses: azure/setup-helm@v4.2.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Fetch npm
        run: npm ci

      - name: Bundle Website
        run: npm run build

      - name: Sanitize
        id: vars
        run: |
          YEAR=$(date +"%Y")
          WEEK_OF_YEAR=$(date +"%-V")
          VERSION="${YEAR}.${WEEK_OF_YEAR}.${GITHUB_RUN_NUMBER}"

          # Append for non main builds a commit hash, so it is marked as snapshot
          if [[ "${GITHUB_REF_NAME}" != "main" ]]; then
            COMMIT_HASH=$(git rev-parse --short "${GITHUB_SHA}")
            VERSION="${VERSION}-${COMMIT_HASH}"
          fi

          REGISTRY_PATH="${GITHUB_REPOSITORY,,}"
          HELM_REPOSITORY="${GITHUB_REPOSITORY_OWNER,,}/helm"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "REGISTRY_PATH=${REGISTRY_PATH}" >> $GITHUB_ENV
          echo "HELM_REPOSITORY=${HELM_REPOSITORY}" >> $GITHUB_ENV
          echo "IMAGE_TAG=git.denktmit.tech/${REGISTRY_PATH}:${VERSION}" >> $GITHUB_ENV

          echo "The following additional environment variables are defined:"
          cat "${GITHUB_ENV}"

      - name: Docker | Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Chart | Push
        uses: https://github.com/appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: sosole
          repository: "${{ env.HELM_REPOSITORY }}"
          # monk trigger! why not naming it VERSION?!
          tag: "${{ env.VERSION }}"
          app_version: "${{ env.VERSION }}"
          registry: 'git.denktmit.tech'
          registry_username: "${{ secrets.CI_ACTOR }}"
          registry_password: "${{ secrets.CI_TOKEN }}"
          update_dependencies: false