{{- if .Values.imagePullSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sosole.imagePullSecret" . }}
  labels:
    {{- include "sosole.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.imagePullSecret.storeName }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .dockerlogin }}` }}"
    name: {{ include "sosole.imagePullSecret" . }}
    creationPolicy: Owner
  data:
    - secretKey: dockerlogin
      remoteRef:
        key: {{ .Values.imagePullSecret.secretId }}
        property: {{ .Values.imagePullSecret.secretProperty }}
{{- end }}
